package com.playground.user.service;

import com.playground.user.converter.AddressConverter;
import com.playground.user.dto.AddressCreationRequestDTO;
import com.playground.user.dto.AddressDTO;
import com.playground.user.exception.UserNotFoundException;
import com.playground.user.model.Address;
import com.playground.user.model.AddressType;
import com.playground.user.repository.AddressRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@RequiredArgsConstructor
@Service
public class AddressService {

    private final AddressRepository addressRepository;
    private final AddressConverter addressConverter;

    public List<AddressDTO> getAll() {
        return addressRepository.findAll().stream()
                .map(addressConverter::toDto)
                .collect(Collectors.toList());
    }

    public AddressDTO getById(UUID id) {
        return addressRepository.findById(id)
                .map(addressConverter::toDto)
                .orElseThrow(UserNotFoundException::new);
    }

    public AddressDTO create(AddressCreationRequestDTO request) {
        Address created = addressRepository.save(addressConverter.toEntity(request));
        return addressConverter.toDto(created);
    }

    public List<AddressDTO> createRandom(Integer quantity) {
        List<Address> toSave = new ArrayList<>();

        for (Integer i = 0; i < quantity; i++) {
            toSave.add(autoGeneratedAddress());
        }

        return addressRepository.saveAll(toSave).stream()
                .map(addressConverter::toDto)
                .collect(Collectors.toList());
    }

    private Address autoGeneratedAddress() {
        Address newAddr = new Address();

        newAddr.setCountry("Auto-generated");
        newAddr.setCity("Auto-generated");
        newAddr.setStreet("Auto-generated");
        newAddr.setHouseNumber("Auto-generated");
        newAddr.setFloor("Auto-generated");
        newAddr.setZipCode("Auto-generated");
        newAddr.setAdditionalAddress("Auto-generated");
        newAddr.setInfo("Auto-generated");
        newAddr.setAddressType(AddressType.BILLING);

        return newAddr;
    }
}
